# Generated by Django 3.0.4 on 2020-04-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecreated',
            new_name='datecompleted',
        ),
    ]
